"use strict";
{
  const _aran_itr = globalThis["_ARAN_INTRINSIC_"];
  let _aran_par_this = this;
  let _aran_par_import = {
    importModule(source) {
      return import(source);
    },
  }.importModule;
  let _aran_var___, _aran_var_state_0, _aran_var_state_1, _aran_var_frame;
  _aran_var___ = _aran_itr["globalThis"]["__aran_advice__"];
  _aran_var_state_0 = false;
  _aran_var_state_1 = _aran_var___["block@setup"](
    _aran_var_state_0,
    "global-eval",
    "$",
  );
  _aran_var_frame = _aran_var___["block@declaration-overwrite"](
    _aran_var_state_1,
    "global-eval",
    {
      __proto__: null,
      ["this"]: _aran_par_this,
      ["import"]: _aran_par_import,
    },
    "$",
  );
  _aran_par_this = _aran_var_frame["this"];
  _aran_par_import = _aran_var_frame["import"];
  _aran_var___["program-block@after"](
    _aran_var_state_1,
    "global-eval",
    _aran_var___["test@before"](
      _aran_var_state_1,
      "conditional",
      _aran_var___["apply@around"](
        _aran_var_state_1,
        _aran_var___["construct@around"](
          _aran_var_state_1,
          _aran_var___["apply@around"](
            _aran_var_state_1,
            _aran_var___["intrinsic@after"](
              _aran_var_state_1,
              "aran.getValueProperty",
              _aran_itr["aran.getValueProperty"],
              "$.body.0.expression.test.callee.callee",
            ),
            _aran_var___["intrinsic@after"](
              _aran_var_state_1,
              "undefined",
              _aran_itr["undefined"],
              "$.body.0.expression.test.callee.callee",
            ),
            [
              _aran_var___["intrinsic@after"](
                _aran_var_state_1,
                "globalThis",
                _aran_itr["globalThis"],
                "$.body.0.expression.test.callee.callee.object",
              ),
              _aran_var___["primitive@after"](
                _aran_var_state_1,
                "Function",
                "$.body.0.expression.test.callee.callee",
              ),
            ],
            "$.body.0.expression.test.callee.callee",
          ),
          [
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "x",
              "$.body.0.expression.test.callee.arguments.0",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "y",
              "$.body.0.expression.test.callee.arguments.1",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "return x + y;",
              "$.body.0.expression.test.callee.arguments.2",
            ),
          ],
          "$.body.0.expression.test.callee",
        ),
        _aran_var___["intrinsic@after"](
          _aran_var_state_1,
          "undefined",
          _aran_itr["undefined"],
          "$.body.0.expression.test.callee",
        ),
        [
          _aran_var___["primitive@after"](
            _aran_var_state_1,
            2,
            "$.body.0.expression.test.arguments.0",
          ),
          _aran_var___["primitive@after"](
            _aran_var_state_1,
            3,
            "$.body.0.expression.test.arguments.1",
          ),
        ],
        "$.body.0.expression.test",
      ),
      "$.body.0.expression",
    )
      ? _aran_var___["primitive@after"](
          _aran_var_state_1,
          null,
          "$.body.0.expression.consequent",
        )
      : _aran_var___["primitive@after"](
          _aran_var_state_1,
          null,
          "$.body.0.expression.alternate",
        ),
    "$",
  );
}

("use strict");
{
  const _aran_itr = globalThis["_ARAN_INTRINSIC_"];
  let _aran_par_this = this;
  let _aran_par_import = {
    importModule(source) {
      return import(source);
    },
  }.importModule;
  let _aran_var___,
    _aran_var_state_0,
    _aran_var_state_1,
    _aran_var_frame,
    _aran_var_$__w_410 = _aran_itr["aran.deadzone_symbol"];
  _aran_var___ = _aran_itr["globalThis"]["__aran_advice__"];
  _aran_var_state_0 = false;
  _aran_var_state_1 = _aran_var___["block@setup"](
    _aran_var_state_0,
    "global-eval",
    "$",
  );
  _aran_var_frame = _aran_var___["block@declaration-overwrite"](
    _aran_var_state_1,
    "global-eval",
    {
      __proto__: null,
      ["this"]: _aran_par_this,
      ["import"]: _aran_par_import,
      [".w.410"]: _aran_var_$__w_410,
    },
    "$",
  );
  _aran_par_this = _aran_var_frame["this"];
  _aran_par_import = _aran_var_frame["import"];
  _aran_var_$__w_410 = _aran_var_frame[".w.410"];
  _aran_var___["program-block@after"](
    _aran_var_state_1,
    "global-eval",
    ((_aran_var_$__w_410 = _aran_var___["closure@after"](
      _aran_var_state_1,
      "function",
      ((_aran_par_function_callee) =>
        (_aran_par_function_callee = function (
          ..._aran_par_function_arguments
        ) {
          let _aran_par_new_target = new.target;
          let _aran_par_this = new.target ? void null : this;
          let _aran_var_state_2,
            _aran_var_frame,
            _aran_var_$__r_4610 = _aran_itr["aran.deadzone_symbol"],
            _aran_var_$__w_4510,
            _aran_var_$_arguments,
            _aran_var_$_x,
            _aran_var_$_y;
          _aran_var_state_2 = _aran_var___["block@setup"](
            _aran_var_state_1,
            "function",
            "$.body.0.expression",
          );
          _aran_var_frame = _aran_var___["block@declaration-overwrite"](
            _aran_var_state_2,
            "function",
            {
              __proto__: null,
              ["this"]: _aran_par_this,
              ["new.target"]: _aran_par_new_target,
              ["function.callee"]: _aran_par_function_callee,
              ["function.arguments"]: _aran_par_function_arguments,
              [".r.4610"]: _aran_var_$__r_4610,
              [".w.4510"]: _aran_var_$__w_4510,
              ["arguments"]: _aran_var_$_arguments,
              ["x"]: _aran_var_$_x,
              ["y"]: _aran_var_$_y,
            },
            "$.body.0.expression",
          );
          _aran_par_this = _aran_var_frame["this"];
          _aran_par_new_target = _aran_var_frame["new.target"];
          _aran_par_function_callee = _aran_var_frame["function.callee"];
          _aran_par_function_arguments = _aran_var_frame["function.arguments"];
          _aran_var_$__r_4610 = _aran_var_frame[".r.4610"];
          _aran_var_$__w_4510 = _aran_var_frame[".w.4510"];
          _aran_var_$_arguments = _aran_var_frame["arguments"];
          _aran_var_$_x = _aran_var_frame["x"];
          _aran_var_$_y = _aran_var_frame["y"];
          _aran_var___["test@before"](
            _aran_var_state_2,
            "conditional",
            _aran_par_new_target,
            "$.body.0.expression",
          )
            ? (_aran_par_this = _aran_var___["apply@around"](
                _aran_var_state_2,
                _aran_var___["intrinsic@after"](
                  _aran_var_state_2,
                  "Object.create",
                  _aran_itr["Object.create"],
                  "$.body.0.expression",
                ),
                _aran_var___["intrinsic@after"](
                  _aran_var_state_2,
                  "undefined",
                  _aran_itr["undefined"],
                  "$.body.0.expression",
                ),
                [
                  ((_aran_var_$__r_4610 = _aran_var___["apply@around"](
                    _aran_var_state_2,
                    _aran_var___["intrinsic@after"](
                      _aran_var_state_2,
                      "aran.getValueProperty",
                      _aran_itr["aran.getValueProperty"],
                      "$.body.0.expression",
                    ),
                    _aran_var___["intrinsic@after"](
                      _aran_var_state_2,
                      "undefined",
                      _aran_itr["undefined"],
                      "$.body.0.expression",
                    ),
                    [
                      _aran_par_new_target,
                      _aran_var___["primitive@after"](
                        _aran_var_state_2,
                        "prototype",
                        "$.body.0.expression",
                      ),
                    ],
                    "$.body.0.expression",
                  )),
                  _aran_var___["test@before"](
                    _aran_var_state_2,
                    "conditional",
                    _aran_var___["test@before"](
                      _aran_var_state_2,
                      "conditional",
                      _aran_var___["apply@around"](
                        _aran_var_state_2,
                        _aran_var___["intrinsic@after"](
                          _aran_var_state_2,
                          "aran.performBinaryOperation",
                          _aran_itr["aran.performBinaryOperation"],
                          "$.body.0.expression",
                        ),
                        _aran_var___["intrinsic@after"](
                          _aran_var_state_2,
                          "undefined",
                          _aran_itr["undefined"],
                          "$.body.0.expression",
                        ),
                        [
                          _aran_var___["primitive@after"](
                            _aran_var_state_2,
                            "===",
                            "$.body.0.expression",
                          ),
                          _aran_var___["apply@around"](
                            _aran_var_state_2,
                            _aran_var___["intrinsic@after"](
                              _aran_var_state_2,
                              "aran.performUnaryOperation",
                              _aran_itr["aran.performUnaryOperation"],
                              "$.body.0.expression",
                            ),
                            _aran_var___["intrinsic@after"](
                              _aran_var_state_2,
                              "undefined",
                              _aran_itr["undefined"],
                              "$.body.0.expression",
                            ),
                            [
                              _aran_var___["primitive@after"](
                                _aran_var_state_2,
                                "typeof",
                                "$.body.0.expression",
                              ),
                              _aran_var_$__r_4610,
                            ],
                            "$.body.0.expression",
                          ),
                          _aran_var___["primitive@after"](
                            _aran_var_state_2,
                            "object",
                            "$.body.0.expression",
                          ),
                        ],
                        "$.body.0.expression",
                      ),
                      "$.body.0.expression",
                    )
                      ? _aran_var___["apply@around"](
                          _aran_var_state_2,
                          _aran_var___["intrinsic@after"](
                            _aran_var_state_2,
                            "aran.performBinaryOperation",
                            _aran_itr["aran.performBinaryOperation"],
                            "$.body.0.expression",
                          ),
                          _aran_var___["intrinsic@after"](
                            _aran_var_state_2,
                            "undefined",
                            _aran_itr["undefined"],
                            "$.body.0.expression",
                          ),
                          [
                            _aran_var___["primitive@after"](
                              _aran_var_state_2,
                              "!==",
                              "$.body.0.expression",
                            ),
                            _aran_var_$__r_4610,
                            _aran_var___["primitive@after"](
                              _aran_var_state_2,
                              null,
                              "$.body.0.expression",
                            ),
                          ],
                          "$.body.0.expression",
                        )
                      : _aran_var___["apply@around"](
                          _aran_var_state_2,
                          _aran_var___["intrinsic@after"](
                            _aran_var_state_2,
                            "aran.performBinaryOperation",
                            _aran_itr["aran.performBinaryOperation"],
                            "$.body.0.expression",
                          ),
                          _aran_var___["intrinsic@after"](
                            _aran_var_state_2,
                            "undefined",
                            _aran_itr["undefined"],
                            "$.body.0.expression",
                          ),
                          [
                            _aran_var___["primitive@after"](
                              _aran_var_state_2,
                              "===",
                              "$.body.0.expression",
                            ),
                            _aran_var___["apply@around"](
                              _aran_var_state_2,
                              _aran_var___["intrinsic@after"](
                                _aran_var_state_2,
                                "aran.performUnaryOperation",
                                _aran_itr["aran.performUnaryOperation"],
                                "$.body.0.expression",
                              ),
                              _aran_var___["intrinsic@after"](
                                _aran_var_state_2,
                                "undefined",
                                _aran_itr["undefined"],
                                "$.body.0.expression",
                              ),
                              [
                                _aran_var___["primitive@after"](
                                  _aran_var_state_2,
                                  "typeof",
                                  "$.body.0.expression",
                                ),
                                _aran_var_$__r_4610,
                              ],
                              "$.body.0.expression",
                            ),
                            _aran_var___["primitive@after"](
                              _aran_var_state_2,
                              "function",
                              "$.body.0.expression",
                            ),
                          ],
                          "$.body.0.expression",
                        ),
                    "$.body.0.expression",
                  )
                    ? _aran_var_$__r_4610
                    : _aran_var___["intrinsic@after"](
                        _aran_var_state_2,
                        "Object.prototype",
                        _aran_itr["Object.prototype"],
                        "$.body.0.expression",
                      )),
                ],
                "$.body.0.expression",
              ))
            : (_aran_par_this = _aran_var___["test@before"](
                _aran_var_state_2,
                "conditional",
                _aran_var___["apply@around"](
                  _aran_var_state_2,
                  _aran_var___["intrinsic@after"](
                    _aran_var_state_2,
                    "aran.performBinaryOperation",
                    _aran_itr["aran.performBinaryOperation"],
                    "$.body.0.expression",
                  ),
                  _aran_var___["intrinsic@after"](
                    _aran_var_state_2,
                    "undefined",
                    _aran_itr["undefined"],
                    "$.body.0.expression",
                  ),
                  [
                    _aran_var___["primitive@after"](
                      _aran_var_state_2,
                      "==",
                      "$.body.0.expression",
                    ),
                    _aran_par_this,
                    _aran_var___["primitive@after"](
                      _aran_var_state_2,
                      null,
                      "$.body.0.expression",
                    ),
                  ],
                  "$.body.0.expression",
                ),
                "$.body.0.expression",
              )
                ? _aran_var___["intrinsic@after"](
                    _aran_var_state_2,
                    "globalThis",
                    _aran_itr["globalThis"],
                    "$.body.0.expression",
                  )
                : _aran_var___["apply@around"](
                    _aran_var_state_2,
                    _aran_var___["intrinsic@after"](
                      _aran_var_state_2,
                      "Object",
                      _aran_itr["Object"],
                      "$.body.0.expression",
                    ),
                    _aran_var___["intrinsic@after"](
                      _aran_var_state_2,
                      "undefined",
                      _aran_itr["undefined"],
                      "$.body.0.expression",
                    ),
                    [_aran_par_this],
                    "$.body.0.expression",
                  ));
          _aran_var_$_arguments = _aran_var___["apply@around"](
            _aran_var_state_2,
            _aran_var___["intrinsic@after"](
              _aran_var_state_2,
              "aran.toArgumentList",
              _aran_itr["aran.toArgumentList"],
              "$.body.0.expression",
            ),
            _aran_var___["intrinsic@after"](
              _aran_var_state_2,
              "undefined",
              _aran_itr["undefined"],
              "$.body.0.expression",
            ),
            [_aran_par_function_arguments, _aran_var_$__w_410],
            "$.body.0.expression",
          );
          _aran_var_$_x = _aran_var___["test@before"](
            _aran_var_state_2,
            "conditional",
            _aran_var___["apply@around"](
              _aran_var_state_2,
              _aran_var___["intrinsic@after"](
                _aran_var_state_2,
                "Object.hasOwn",
                _aran_itr["Object.hasOwn"],
                "$.body.0.expression.params.0",
              ),
              _aran_var___["intrinsic@after"](
                _aran_var_state_2,
                "undefined",
                _aran_itr["undefined"],
                "$.body.0.expression.params.0",
              ),
              [
                _aran_par_function_arguments,
                _aran_var___["primitive@after"](
                  _aran_var_state_2,
                  0,
                  "$.body.0.expression.params.0",
                ),
              ],
              "$.body.0.expression.params.0",
            ),
            "$.body.0.expression.params.0",
          )
            ? _aran_var___["apply@around"](
                _aran_var_state_2,
                _aran_var___["intrinsic@after"](
                  _aran_var_state_2,
                  "aran.getValueProperty",
                  _aran_itr["aran.getValueProperty"],
                  "$.body.0.expression.params.0",
                ),
                _aran_var___["intrinsic@after"](
                  _aran_var_state_2,
                  "undefined",
                  _aran_itr["undefined"],
                  "$.body.0.expression.params.0",
                ),
                [
                  _aran_par_function_arguments,
                  _aran_var___["primitive@after"](
                    _aran_var_state_2,
                    0,
                    "$.body.0.expression.params.0",
                  ),
                ],
                "$.body.0.expression.params.0",
              )
            : _aran_var___["intrinsic@after"](
                _aran_var_state_2,
                "undefined",
                _aran_itr["undefined"],
                "$.body.0.expression.params.0",
              );
          _aran_var_$_y = _aran_var___["test@before"](
            _aran_var_state_2,
            "conditional",
            _aran_var___["apply@around"](
              _aran_var_state_2,
              _aran_var___["intrinsic@after"](
                _aran_var_state_2,
                "Object.hasOwn",
                _aran_itr["Object.hasOwn"],
                "$.body.0.expression.params.1",
              ),
              _aran_var___["intrinsic@after"](
                _aran_var_state_2,
                "undefined",
                _aran_itr["undefined"],
                "$.body.0.expression.params.1",
              ),
              [
                _aran_par_function_arguments,
                _aran_var___["primitive@after"](
                  _aran_var_state_2,
                  1,
                  "$.body.0.expression.params.1",
                ),
              ],
              "$.body.0.expression.params.1",
            ),
            "$.body.0.expression.params.1",
          )
            ? _aran_var___["apply@around"](
                _aran_var_state_2,
                _aran_var___["intrinsic@after"](
                  _aran_var_state_2,
                  "aran.getValueProperty",
                  _aran_itr["aran.getValueProperty"],
                  "$.body.0.expression.params.1",
                ),
                _aran_var___["intrinsic@after"](
                  _aran_var_state_2,
                  "undefined",
                  _aran_itr["undefined"],
                  "$.body.0.expression.params.1",
                ),
                [
                  _aran_par_function_arguments,
                  _aran_var___["primitive@after"](
                    _aran_var_state_2,
                    1,
                    "$.body.0.expression.params.1",
                  ),
                ],
                "$.body.0.expression.params.1",
              )
            : _aran_var___["intrinsic@after"](
                _aran_var_state_2,
                "undefined",
                _aran_itr["undefined"],
                "$.body.0.expression.params.1",
              );
          break_return: {
            let _aran_var_state_3, _aran_var_frame;
            _aran_var_state_3 = _aran_var___["block@setup"](
              _aran_var_state_2,
              "bare",
              "$.body.0.expression.body",
            );
            _aran_var_frame = _aran_var___["block@declaration-overwrite"](
              _aran_var_state_3,
              "bare",
              (null, _aran_itr["aran.createObject"])(null),
              "$.body.0.expression.body",
            );
            _aran_var_$__w_4510 = _aran_var___["apply@around"](
              _aran_var_state_3,
              _aran_var___["intrinsic@after"](
                _aran_var_state_3,
                "aran.performBinaryOperation",
                _aran_itr["aran.performBinaryOperation"],
                "$.body.0.expression.body.body.0.argument",
              ),
              _aran_var___["intrinsic@after"](
                _aran_var_state_3,
                "undefined",
                _aran_itr["undefined"],
                "$.body.0.expression.body.body.0.argument",
              ),
              [
                _aran_var___["primitive@after"](
                  _aran_var_state_3,
                  "+",
                  "$.body.0.expression.body.body.0.argument",
                ),
                _aran_var_$_x,
                _aran_var_$_y,
              ],
              "$.body.0.expression.body.body.0.argument",
            );
            break break_return;
          }
          return _aran_var___["closure-block@after"](
            _aran_var_state_2,
            "function",
            _aran_var___["test@before"](
              _aran_var_state_2,
              "conditional",
              _aran_par_new_target,
              "$.body.0.expression",
            )
              ? _aran_var___["test@before"](
                  _aran_var_state_2,
                  "conditional",
                  _aran_var___["test@before"](
                    _aran_var_state_2,
                    "conditional",
                    _aran_var___["apply@around"](
                      _aran_var_state_2,
                      _aran_var___["intrinsic@after"](
                        _aran_var_state_2,
                        "aran.performBinaryOperation",
                        _aran_itr["aran.performBinaryOperation"],
                        "$.body.0.expression",
                      ),
                      _aran_var___["intrinsic@after"](
                        _aran_var_state_2,
                        "undefined",
                        _aran_itr["undefined"],
                        "$.body.0.expression",
                      ),
                      [
                        _aran_var___["primitive@after"](
                          _aran_var_state_2,
                          "===",
                          "$.body.0.expression",
                        ),
                        _aran_var___["apply@around"](
                          _aran_var_state_2,
                          _aran_var___["intrinsic@after"](
                            _aran_var_state_2,
                            "aran.performUnaryOperation",
                            _aran_itr["aran.performUnaryOperation"],
                            "$.body.0.expression",
                          ),
                          _aran_var___["intrinsic@after"](
                            _aran_var_state_2,
                            "undefined",
                            _aran_itr["undefined"],
                            "$.body.0.expression",
                          ),
                          [
                            _aran_var___["primitive@after"](
                              _aran_var_state_2,
                              "typeof",
                              "$.body.0.expression",
                            ),
                            _aran_var_$__w_4510,
                          ],
                          "$.body.0.expression",
                        ),
                        _aran_var___["primitive@after"](
                          _aran_var_state_2,
                          "object",
                          "$.body.0.expression",
                        ),
                      ],
                      "$.body.0.expression",
                    ),
                    "$.body.0.expression",
                  )
                    ? _aran_var___["apply@around"](
                        _aran_var_state_2,
                        _aran_var___["intrinsic@after"](
                          _aran_var_state_2,
                          "aran.performBinaryOperation",
                          _aran_itr["aran.performBinaryOperation"],
                          "$.body.0.expression",
                        ),
                        _aran_var___["intrinsic@after"](
                          _aran_var_state_2,
                          "undefined",
                          _aran_itr["undefined"],
                          "$.body.0.expression",
                        ),
                        [
                          _aran_var___["primitive@after"](
                            _aran_var_state_2,
                            "!==",
                            "$.body.0.expression",
                          ),
                          _aran_var_$__w_4510,
                          _aran_var___["primitive@after"](
                            _aran_var_state_2,
                            null,
                            "$.body.0.expression",
                          ),
                        ],
                        "$.body.0.expression",
                      )
                    : _aran_var___["apply@around"](
                        _aran_var_state_2,
                        _aran_var___["intrinsic@after"](
                          _aran_var_state_2,
                          "aran.performBinaryOperation",
                          _aran_itr["aran.performBinaryOperation"],
                          "$.body.0.expression",
                        ),
                        _aran_var___["intrinsic@after"](
                          _aran_var_state_2,
                          "undefined",
                          _aran_itr["undefined"],
                          "$.body.0.expression",
                        ),
                        [
                          _aran_var___["primitive@after"](
                            _aran_var_state_2,
                            "===",
                            "$.body.0.expression",
                          ),
                          _aran_var___["apply@around"](
                            _aran_var_state_2,
                            _aran_var___["intrinsic@after"](
                              _aran_var_state_2,
                              "aran.performUnaryOperation",
                              _aran_itr["aran.performUnaryOperation"],
                              "$.body.0.expression",
                            ),
                            _aran_var___["intrinsic@after"](
                              _aran_var_state_2,
                              "undefined",
                              _aran_itr["undefined"],
                              "$.body.0.expression",
                            ),
                            [
                              _aran_var___["primitive@after"](
                                _aran_var_state_2,
                                "typeof",
                                "$.body.0.expression",
                              ),
                              _aran_var_$__w_4510,
                            ],
                            "$.body.0.expression",
                          ),
                          _aran_var___["primitive@after"](
                            _aran_var_state_2,
                            "function",
                            "$.body.0.expression",
                          ),
                        ],
                        "$.body.0.expression",
                      ),
                  "$.body.0.expression",
                )
                ? _aran_var_$__w_4510
                : _aran_par_this
              : _aran_var_$__w_4510,
            "$.body.0.expression",
          );
        }))(),
      "$.body.0.expression",
    )),
    _aran_var___["apply@around"](
      _aran_var_state_1,
      _aran_var___["intrinsic@after"](
        _aran_var_state_1,
        "Reflect.defineProperty",
        _aran_itr["Reflect.defineProperty"],
        "$.body.0.expression",
      ),
      _aran_var___["intrinsic@after"](
        _aran_var_state_1,
        "undefined",
        _aran_itr["undefined"],
        "$.body.0.expression",
      ),
      [
        _aran_var_$__w_410,
        _aran_var___["primitive@after"](
          _aran_var_state_1,
          "length",
          "$.body.0.expression",
        ),
        _aran_var___["apply@around"](
          _aran_var_state_1,
          _aran_var___["intrinsic@after"](
            _aran_var_state_1,
            "aran.createObject",
            _aran_itr["aran.createObject"],
            "$.body.0.expression",
          ),
          _aran_var___["intrinsic@after"](
            _aran_var_state_1,
            "undefined",
            _aran_itr["undefined"],
            "$.body.0.expression",
          ),
          [
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              null,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "value",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              2,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "writable",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              false,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "enumerable",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              false,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "configurable",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              true,
              "$.body.0.expression",
            ),
          ],
          "$.body.0.expression",
        ),
      ],
      "$.body.0.expression",
    ),
    _aran_var___["apply@around"](
      _aran_var_state_1,
      _aran_var___["intrinsic@after"](
        _aran_var_state_1,
        "Reflect.defineProperty",
        _aran_itr["Reflect.defineProperty"],
        "$.body.0.expression",
      ),
      _aran_var___["intrinsic@after"](
        _aran_var_state_1,
        "undefined",
        _aran_itr["undefined"],
        "$.body.0.expression",
      ),
      [
        _aran_var_$__w_410,
        _aran_var___["primitive@after"](
          _aran_var_state_1,
          "name",
          "$.body.0.expression",
        ),
        _aran_var___["apply@around"](
          _aran_var_state_1,
          _aran_var___["intrinsic@after"](
            _aran_var_state_1,
            "aran.createObject",
            _aran_itr["aran.createObject"],
            "$.body.0.expression",
          ),
          _aran_var___["intrinsic@after"](
            _aran_var_state_1,
            "undefined",
            _aran_itr["undefined"],
            "$.body.0.expression",
          ),
          [
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              null,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "value",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "anonymous",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "writable",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              false,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "enumerable",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              false,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "configurable",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              true,
              "$.body.0.expression",
            ),
          ],
          "$.body.0.expression",
        ),
      ],
      "$.body.0.expression",
    ),
    _aran_var___["apply@around"](
      _aran_var_state_1,
      _aran_var___["intrinsic@after"](
        _aran_var_state_1,
        "Reflect.defineProperty",
        _aran_itr["Reflect.defineProperty"],
        "$.body.0.expression",
      ),
      _aran_var___["intrinsic@after"](
        _aran_var_state_1,
        "undefined",
        _aran_itr["undefined"],
        "$.body.0.expression",
      ),
      [
        _aran_var_$__w_410,
        _aran_var___["primitive@after"](
          _aran_var_state_1,
          "arguments",
          "$.body.0.expression",
        ),
        _aran_var___["apply@around"](
          _aran_var_state_1,
          _aran_var___["intrinsic@after"](
            _aran_var_state_1,
            "aran.createObject",
            _aran_itr["aran.createObject"],
            "$.body.0.expression",
          ),
          _aran_var___["intrinsic@after"](
            _aran_var_state_1,
            "undefined",
            _aran_itr["undefined"],
            "$.body.0.expression",
          ),
          [
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              null,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "value",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              null,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "writable",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              false,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "enumerable",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              false,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "configurable",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              true,
              "$.body.0.expression",
            ),
          ],
          "$.body.0.expression",
        ),
      ],
      "$.body.0.expression",
    ),
    _aran_var___["apply@around"](
      _aran_var_state_1,
      _aran_var___["intrinsic@after"](
        _aran_var_state_1,
        "Reflect.defineProperty",
        _aran_itr["Reflect.defineProperty"],
        "$.body.0.expression",
      ),
      _aran_var___["intrinsic@after"](
        _aran_var_state_1,
        "undefined",
        _aran_itr["undefined"],
        "$.body.0.expression",
      ),
      [
        _aran_var_$__w_410,
        _aran_var___["primitive@after"](
          _aran_var_state_1,
          "caller",
          "$.body.0.expression",
        ),
        _aran_var___["apply@around"](
          _aran_var_state_1,
          _aran_var___["intrinsic@after"](
            _aran_var_state_1,
            "aran.createObject",
            _aran_itr["aran.createObject"],
            "$.body.0.expression",
          ),
          _aran_var___["intrinsic@after"](
            _aran_var_state_1,
            "undefined",
            _aran_itr["undefined"],
            "$.body.0.expression",
          ),
          [
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              null,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "value",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              null,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "writable",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              false,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "enumerable",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              false,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "configurable",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              true,
              "$.body.0.expression",
            ),
          ],
          "$.body.0.expression",
        ),
      ],
      "$.body.0.expression",
    ),
    _aran_var___["apply@around"](
      _aran_var_state_1,
      _aran_var___["intrinsic@after"](
        _aran_var_state_1,
        "Reflect.defineProperty",
        _aran_itr["Reflect.defineProperty"],
        "$.body.0.expression",
      ),
      _aran_var___["intrinsic@after"](
        _aran_var_state_1,
        "undefined",
        _aran_itr["undefined"],
        "$.body.0.expression",
      ),
      [
        _aran_var_$__w_410,
        _aran_var___["primitive@after"](
          _aran_var_state_1,
          "prototype",
          "$.body.0.expression",
        ),
        _aran_var___["apply@around"](
          _aran_var_state_1,
          _aran_var___["intrinsic@after"](
            _aran_var_state_1,
            "aran.createObject",
            _aran_itr["aran.createObject"],
            "$.body.0.expression",
          ),
          _aran_var___["intrinsic@after"](
            _aran_var_state_1,
            "undefined",
            _aran_itr["undefined"],
            "$.body.0.expression",
          ),
          [
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              null,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "value",
              "$.body.0.expression",
            ),
            _aran_var___["apply@around"](
              _aran_var_state_1,
              _aran_var___["intrinsic@after"](
                _aran_var_state_1,
                "Object.defineProperty",
                _aran_itr["Object.defineProperty"],
                "$.body.0.expression",
              ),
              _aran_var___["intrinsic@after"](
                _aran_var_state_1,
                "undefined",
                _aran_itr["undefined"],
                "$.body.0.expression",
              ),
              [
                _aran_var___["apply@around"](
                  _aran_var_state_1,
                  _aran_var___["intrinsic@after"](
                    _aran_var_state_1,
                    "Object.create",
                    _aran_itr["Object.create"],
                    "$.body.0.expression",
                  ),
                  _aran_var___["intrinsic@after"](
                    _aran_var_state_1,
                    "undefined",
                    _aran_itr["undefined"],
                    "$.body.0.expression",
                  ),
                  [
                    _aran_var___["intrinsic@after"](
                      _aran_var_state_1,
                      "Object.prototype",
                      _aran_itr["Object.prototype"],
                      "$.body.0.expression",
                    ),
                  ],
                  "$.body.0.expression",
                ),
                _aran_var___["primitive@after"](
                  _aran_var_state_1,
                  "constructor",
                  "$.body.0.expression",
                ),
                _aran_var___["apply@around"](
                  _aran_var_state_1,
                  _aran_var___["intrinsic@after"](
                    _aran_var_state_1,
                    "aran.createObject",
                    _aran_itr["aran.createObject"],
                    "$.body.0.expression",
                  ),
                  _aran_var___["intrinsic@after"](
                    _aran_var_state_1,
                    "undefined",
                    _aran_itr["undefined"],
                    "$.body.0.expression",
                  ),
                  [
                    _aran_var___["primitive@after"](
                      _aran_var_state_1,
                      null,
                      "$.body.0.expression",
                    ),
                    _aran_var___["primitive@after"](
                      _aran_var_state_1,
                      "value",
                      "$.body.0.expression",
                    ),
                    _aran_var_$__w_410,
                    _aran_var___["primitive@after"](
                      _aran_var_state_1,
                      "writable",
                      "$.body.0.expression",
                    ),
                    _aran_var___["primitive@after"](
                      _aran_var_state_1,
                      true,
                      "$.body.0.expression",
                    ),
                    _aran_var___["primitive@after"](
                      _aran_var_state_1,
                      "enumerable",
                      "$.body.0.expression",
                    ),
                    _aran_var___["primitive@after"](
                      _aran_var_state_1,
                      false,
                      "$.body.0.expression",
                    ),
                    _aran_var___["primitive@after"](
                      _aran_var_state_1,
                      "configurable",
                      "$.body.0.expression",
                    ),
                    _aran_var___["primitive@after"](
                      _aran_var_state_1,
                      true,
                      "$.body.0.expression",
                    ),
                  ],
                  "$.body.0.expression",
                ),
              ],
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "writable",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              true,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "enumerable",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              false,
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              "configurable",
              "$.body.0.expression",
            ),
            _aran_var___["primitive@after"](
              _aran_var_state_1,
              false,
              "$.body.0.expression",
            ),
          ],
          "$.body.0.expression",
        ),
      ],
      "$.body.0.expression",
    ),
    _aran_var_$__w_410),
    "$",
  );
}
