/** @type {{[key in import("./stage-name").StageName]: null}} */
export const STAGE_ENUM = {
  "-bare-basic-flexible": null,
  "-bare-basic-standard": null,
  "-bare-patch-flexible": null,
  "-bare-patch-standard": null,
  "-bare-weave-flexible": null,
  "-bare-weave-standard": null,
  "-full-basic-flexible": null,
  "-full-basic-standard": null,
  "-invariant": null,
  "-standard-full": null,
  "-standard-void": null,
  "-state-flexible": null,
  "-trace": null,
  "-track-origin": null,
  "bare-comp": null,
  "bare-main": null,
  "identity": null,
  "parsing": null,
  "stnd-full": null,
  "stnd-void": null,
};
