import type { StringHash } from "./hash";

export type Path = StringHash;

export type Segment =
  | number
  | "meta"
  | "label"
  | "exported"
  | "local"
  | "imported"
  | "cases"
  | "discriminant"
  | "update"
  | "key"
  | "value"
  | "properties"
  | "elements"
  | "id"
  | "params"
  | "callee"
  | "arguments"
  | "test"
  | "init"
  | "declarations"
  | "finalizer"
  | "expressions"
  | "source"
  | "expression"
  | "handler"
  | "consequent"
  | "alternate"
  | "declaration"
  | "specifiers"
  | "superClass"
  | "object"
  | "tag"
  | "property"
  | "argument"
  | "left"
  | "param"
  | "right"
  | "block"
  | "body"
  | "quasi"
  | "quasis";
