title: Aran
author: Laurent Christophe
email: laurent.christophe.terken@gmail.com
description: Documentation for Aran, a JavaScript Instrumentation Library
theme: minima
source: doc/src
destination: doc/out
collections:
  issues:
    output: true
    permalink: /issues/:name
  demos:
    output: true
    permalink: /demos/:name
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
header_pages:
  - start.md
  - api.md
  - typedoc.md
  - issues.md
  - demo.md
github_username: lachrist
