node test/262/main/batch.mjs \
  identity \
  parsing-main \
  parsing-comp \
  bare-main \
  bare-comp \
  stnd-void \
  stnd-full \
  linvail/cust-main \
  linvail/cust-comp \
  linvail/stnd-main \
  linvail/stnd-comp \
  provenancy/count/main \
  provenancy/count/comp \
  provenancy/track/stack-main \
  provenancy/track/stack-comp \
  provenancy/track/intra-main \
  provenancy/track/intra-comp \
  provenancy/track/inter-main \
  provenancy/track/inter-comp \
  provenancy/track/store-main \
  provenancy/track/store-comp-internal \
  provenancy/track/store-comp-external \
